### ISSUE TITLE
Epidemics must start with 0 cases

### ISSUE THREAD

**Issue by khwilson** [HopkinsIDD/COVIDScenarioPipeline#95]
It appears that if you start your epidemic with > 0 cases somewhere in your model, the filtering mechanisms ends up filtering all simulations and all model_outputs end up with straight `-1`s. This was verified with @jkamins7 .

Relevant part of config for reproducing. Assumes you're using the COVID_minimal pipeline.

```yaml

start_date: 2020-01-31
end_date: 2020-10-01

spatial_setup:
  census_year: 2010
  base_path: data
  modeled_states: # To model a region that is not a state, remove modeled_states and the importation: block
   - RI
   - MA
   - CT
```
